language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.1
      compiler: clang
      env: COMPILER=clang++-5.0;
    - os: linux
      dist: trusty
      compiler: gcc
      env: COMPILER=g++-6;
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6

install:
  - |    
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      which cmake || brew install cmake;
    fi
  - export CXX=${COMPILER};
  - ${CXX} --version

before_script:
  - g++ --version
  - gcc --version
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake ..

script:
  - cmake --build .
  - ctest