language: cpp

services:
  - docker

# jobs:
#   - include:
#     - stage: build
#       script

stages:
  - format
  - compile

# matrix:
jobs:
  include:
    - stage: compile
      os: osx
      osx_image: xcode9.1
      compiler: clang
      env: COMPILER=clang++;
    - stage: compile
      os: linux
      dist: trusty
      compiler: gcc
      env: COMPILER=g++-6;
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
    - stage: format
      osx: linux
      dist: trusty
      install: skip
      script: docker build -t support/clang-format -f ./support/clang-format/Dockerfile .


# before_install:
#   - cd ${TRAVIS_BUILD_DIR}
#   - docker build -t support/clang-format -f ./support/clang-format/Dockerfile .
#   - docker run support/clang-format

install:
  - export CXX=${COMPILER};
  - ${CXX} --version

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build

script:
  - cmake .. && cmake --build .
  - ctest