language: cpp

services:
  - docker

stages:
  - compile
  - format

jobs:
  include:
    - stage: compile
      os: osx
      osx_image: xcode9.1
      compiler: clang
      env: COMPILER=clang++;
    - stage: compile
      os: linux
      dist: trusty
      compiler: gcc
      env: COMPILER=g++-6;
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
    - stage: format
      osx: linux
      dist: trusty
      install: skip
      before_script: skip
      script:
        - cd ${TRAVIS_BUILD_DIR}
        - sh ./check-clang-format.sh

install:
  - export CXX=${COMPILER};
  - ${CXX} --version

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build

script:
  - cmake .. && cmake --build .
  - ctest