language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.1
      compiler: clang

install:
  - |    
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      which cmake || brew install cmake;
    fi

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake ..

script:
  - pwd
  - ls
  - cmake --build .
  - ctest