language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.1
      compiler: clang
      env: CXX=clang++-5.0;
    - os: linux
      dist: trusty
      compiler: gcc
      env: CXX=g++-6;
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6

before_script:
  - ${CXX} --version
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake ..

script:
  - cmake --build .
  - ctest