language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.1
      compiler: clang
      env: COMPILER='clang++' CPP14=1

install:
  - |    
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      which cmake || brew install cmake;
    fi

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - cmake ..

script:
  - cmake --build .
  - ctest