language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.1
      compiler: clang
    - os: linux
      dist: trusty
      compiler: gcc

install:
  - |    
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      which cmake || brew install cmake;
    fi

before_script:
  - g++ --version
  - gcc --version
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir build && cd build
  - cmake ..

script:
  - cmake --build .
  - ctest