version: '{branch}__build#{build}'
image: Visual Studio 2017
install:
- cmd: git submodule update --init
build_script:
- cmd: >-
    mkdir build && cd build

    cmake .. && cmake --build .
test_script:
- cmd: >-
    ctest -C Release